cloud:
  aws:
    credentials:
      accessKey: ${/spring-boot-aws/cloud-parameter-store/AWS_ACCESS_KEY}
      secretKey: ${/spring-boot-aws/cloud-parameter-store/AWS_SECRET_KEY}
    s3:
      bucket: mifunding
    region:
      static: ap-northeast-2
    stack:
      auto: 'false'



awsParameterStorePropertySource:
  enabled: true

spring:
  datasource:
    url: jdbc:mysql://${/spring-boot-aws/cloud-parameter-store/RDS_ENDPOINT}:3306/mifunding?serverTimezone=Asia/Seoul&useSSL=false&characterEncoding=UTF-8
    username: root
    password: ${/spring-boot-aws/cloud-parameter-store/MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: ${/spring-boot-aws/cloud-parameter-store/G_CLIENT_ID}
            clientSecret: ${/spring-boot-aws/cloud-parameter-store/G_CLIENT_SECRET}
            scope:
              - email
              - profile
logging:
  level:
    org:
      springframework:
        orm:
          jpa: DEBUG
server:
  servlet:
    encoding:
      force-response: true
mail:
  address:
    admin: ${/spring-boot-aws/cloud-parameter-store/ADMIN}
jwt:
  key: ${/spring-boot-aws/cloud-parameter-store/JWT_SECRET_KEY}
  access-token-expiration-minutes: 40
  refresh-token-expiration-minutes: 420

